# arxivの学問領域の指定
subject: 'cat:cs.*'

# 検索キーワード
keywords:
#         reinforcement learning: 3
        world model: 3
        world models: 3
#         internal world: 3
        
# 通知の閾値
score_threshold: 3
